#!/bin/sh                                                                                  	 
                                                                                            	 
trap 'echo Received SIGTERM, finishing; exit' SIGTERM; echo WAITING; while :; do sleep 0.1; done
