#!/bin/sh                                                                                  	 
                                                                                            	 
if test -e /uh-oh; then                                                                    	 	 
 	exit 1                                                                                 	 
else                                                                                       	                                              	 
 	exit 0                                                                                 	 
fi